# 使用散列技巧的单词级的 one-hot 编码（简单示例）

In [8]:
import numpy as np

In [9]:
samples = ['The cat sat on the mat.', 'The dog ate my homework.']

In [10]:
dimensionality = 1000 # 将单词保存为长度为 1000 的向量。如果单词数量接近 1000 个（或更多），将会遇到很多散列冲突，这会降低这种编码方法的准确性

In [11]:
max_length = 10

In [12]:
results = np.zeros((len(samples), max_length, dimensionality))

In [13]:
for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_length]:
        index = abs(hash(word)) % dimensionality # 将单词散列为 0-1000 范围内的一个随机整数索引
        results[i, j, index] = 1.

In [14]:
print(results)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
